#!/bin/bash

SKIP=false;
ASK=true
SPEED=1

for i in "$@"
do
case $i in
    -s|--skip)
    SKIP=true
    ;;
    -d|--dont-ask)
    ASK=false
    ;;
    [0-9]*)
	SPEED=$i
    ;;
    *)
            # unknown option
    ;;
esac
done

lines=$(tput lines)
columns=$(tput cols)
if [ $lines -lt 30 ] || [ $columns -lt 150 ]
then
if [ $# -eq 0 ] || [ "$ask" = true ]
	then
while true; do
    read -p "This will now change the size of terminal. Do you wish to continue?(y/n)
" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) echo "OK, have this at least."; echo "FUCK!";exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
fi
printf '\e[8;30;150t'
echo ""

fi

if [ "$SKIP" = true ]
	then
echo "
FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!         FUCK!FUCK!      FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!        FUCK!FUCK!       FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!       FUCK!FUCK!        FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!      FUCK!FUCK!         FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!    FUCK!FUCK!           FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!   FUCK!FUCK!            FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!  FUCK!FUCK!             FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK! FUCK!FUCK!              FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!FUCK!FUCK!               FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!               FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!UCK!FUCK!                FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!               FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!UCK!FUCK!                FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!               FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!CK!FUCK!                 FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!               FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!UCK!FUCK!                FUCK!FUCK!
FUCK!FUCK!FUCK!FUCK!               FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!FUCK!FUCK!               FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK! FUCK!FUCK!              FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!  FUCK!FUCK!             FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!   FUCK!FUCK!            FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!    FUCK!FUCK!           FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!     FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!                         FUCK!FUCK!      FUCK!FUCK!         
FUCK!FUCK!                         FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!       FUCK!FUCK!        FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!        FUCK!FUCK!       FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!         FUCK!FUCK!      FUCK!FUCK!
FUCK!FUCK!                         FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!FUCK!FUCK!FUCK!FUCK!     FUCK!FUCK!          FUCK!FUCK!     FUCK!FUCK!"
	else

SLEEPTIME=$(echo "scale=20; 0.02/$SPEED" | bc)

echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "UCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "UCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "CK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "UCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "   "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "  "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "    "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n " "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo ""
echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; echo -n "FUCK!"; sleep $SLEEPTIME; sleep $SLEEPTIME; echo ""
echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo -n "     "; sleep $SLEEPTIME; echo ""
	fi

if [ $lines -lt 30 ] || [ $columns -lt 150 ] && [ "$ASK" = true ]
then
while true; do
    read -p "Do you wish to return terminal to initial size?(y/n)
" yn
    case $yn in
        [Yy]* ) clear; resize -s $lines $columns 1>/dev/null; clear; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
	esac
done
fi
